### ISSUE TITLE
pages/volunteer.html-updating-html

### ISSUE THREAD

**Issue by Ibrahim86Ali** [HYF-Class20/agile-development-group3-hyf-redesign#37]
# Task 

Adding the third page of HYF ``` volunteer.html``` 

```html```
- [x] adding full page html elements

```Css```
- [x] adding 90% of the page css elements

## Status 
- [x] In progress
- [] Need Revision 
- [ ] Done 

- Setup: GitHub
  - [ ] created this issue
  - [ ] assigned myself
  - [ ] moved the issue to the project board and added it to the appropriate
        column
- Setup: local
  - [ ] pulled the most recent code from `main`/`master`
  - [ ] created a new `feat-branch-name` branch for my feature

- Before pushing my branch:
  - [ ] pulled the most recent code from `main`/`master` to my feature branch
  - [ ] ran code quality checks
  - [ ] formatted the code
  - [ ] fixed all linting mistakes
- After pushing my branch:
  - [ ] created a new PR linked to this issue
  - [ ] make sure all of the checks passed
  - [ ] assigned someone to review and merge my PR (if the task is ready)
  - [ ] moved the issue to the appropriate column in the project board to review
        it (if the task is ready)
